name: Cargo-audit, lint and test

on:
  push:
    branches: main
  pull_request:
    branches: main

defaults:
  run:
    shell: bash
    working-directory: .

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable

jobs:
  cargo-audit:
    name: cargo audit
    runs-on: ubuntu-latest
    steps:
      - name: Cache cargo-audit version
        uses: Swatinem/rust-cache@v1

      - name: Download cargo-audit
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest

      - name: Run cargo-audit # Using args from .cargo/audit.toml
        run: cargo audit

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev postgresql

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Cache build files
        uses: Swatinem/rust-cache@v1

      - name: Cargo fmt
        run: cargo fmt -- --check
        
      - name: Cargo clippy
        run: cargo clippy --all-targets -- --deny=warnings